### ISSUE TITLE
Setting up for windows users

### ISSUE THREAD

**Issue by moorepants** [kwmsmith/scipy-2017-cython-tutorial#1]
Kurt,

We are putting together this tutorial: https://github.com/sympy/scipy-2017-codegen-tutorial and are trying to figure out the easiest setup for Windows users so that cython works. Can you recommend what you are doing for your tutorial to us?

cc @ixjlyons @bjodah @asmeurer

**Comment by kwmsmith** [comment]
In the [README](https://github.com/kwmsmith/scipy-2017-cython-tutorial/blob/master/README.md) I have several notes asking for help from tutorial-ees using Windows.

I'm currently recommending that everyone use the jupyter docker notebook images, specifically the [scipy-notebook](https://hub.docker.com/r/jupyter/scipy-notebook/).  I realize this won't be a solution for everyone.

Check back now and then for updates to the README for the Windows-native solution.

**Comment by asmeurer** [comment]
I wish our tutorials weren't at the same time. Some folks might want to do both (and I would have like to have gone to yours too).

**Comment by moorepants** [comment]
At least they will get cython in both :)

**Comment by kwmsmith** [comment]
> I wish our tutorials weren't at the same time. Some folks might want to do both (and I would have like to have gone to yours too).

Agreed -- I'd like to go to yours, too, especially since you're generating some non-trivial Cython code, very interesting...
